## number of instances
##
replicaCount: 1

## restart policy for all containers
##
restartPolicy: Always

image:
  repository: mike7515/argocd-ecr-updater # CHANGE_ME - there is currently no published image
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: ""

cronjob:
  name: argocd-ecr-updater-cronjob
  argoNamespace: default
  awsRegion: default
  awsAccount: default
  argocdRepoSecretName: default
  cronExpression: 0 0/6 * * *

serviceAccount:
  create: true
# Recommended to use pod-iam
#    eks.amazonaws.com/role-arn: "arn:aws:iam::1234567890:role/argocd-ecr-updater-iam-role"
  annotations: {}

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

priorityClassName: ""

nodeSelector: {}
#  kubernetes.io/os: linux
#  kubernetes.io/arch: amd64

tolerations: {}

podAnnotations: {}
#  sidecar.istio.io/inject: "false"
#  prometheus.io/scrape: "true"
#  prometheus.io/path: "metrics"
#  prometheus.io/port: "8080"

service:
  httpPort: "8080"

affinity: {}

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
envFromSecret: ""

extraEnvSecrets: {}

# A list of secrets and their paths to mount inside the pod
# This is useful for mounting certificates for security
secretMounts: []
